### ISSUE TITLE
not collecting all traffic

### ISSUE THREAD

**Issue by kjyv** [julioverne/NtSpeed#1]
Hey thanks for your application. I got the impression though that the number is not always reliable. Sometimes it is obviously too small, sometimes no traffic is shown even though e.g. an app is installed from the app store and there is also the ios network notification spinning in the status bar. I'd say it works alright if wireless is not enabled (my device uses the same wireless interface en0, just checked).

**Comment by julioverne** [comment]
fixed in 0.2~beta3
