### ISSUE TITLE
Can you update it 

### ISSUE THREAD

**Issue by tangwanting** [julioverne/NtSpeed#2]
It doesn't work ,10.2

**Comment by zencowboy007** [comment]
Yeah, no good yet on 10.2. Love this tweak on 9.33 iPhone

**Comment by coderov** [comment]
Works on 10.2 very well.
Is possible to add app name when showing speed?

**Comment by zencowboy007** [comment]
It seems to work today but no app name.

Thanks for your time!
Kindly, Chris Buck

**Comment by julioverne** [comment]
iOS 10.2 issue is rotation only.. shold fixed in 0.2~beta
